#!/bin/sh
#BSUB -q nancy
#BSUB -J icy1
#BSUB -n 16
#BSUB -u rmarcus@cfa.harvard.edu
#BSUB -o file.out
#BSUB -e file.err
#BSUB -a openmpi
#BSUB -N


# export PATH=/n/lsf/6.2/linux2.6-glibc2.3-x86/etc:/n/lsf/6.2/linux2.6-glibc2.3-x86/bin:/bin:/usr/bin:/usr/X11R6/bin:/usr/local/bin:/n/home/external/tjcox/bin

ulimit -l unlimited

# echo $LSB_HOSTS | sed -e 's/ /\n/g'  > node.list
# export NPROCS=`wc -l ./node.list | awk '{print $1}'`

# cat node.list
# echo $NPROCS

cp $LSB_DJOB_HOSTFILE node.list
# echo $LSB_DJOB_HOSTFILE | sed -e 's/ /\n/g'  > node.list
# export NPROCS=`wc -l ./node.list | awk '{print $1}'`
let NPROC=0
let NNODE=0
let NCORE=0

for machine in `cat $LSB_DJOB_HOSTFILE`
do
        let NPROC=NPROC+1
	let NCORE=NCORE+1
	if [ $NCORE == 8 ];
	then
	    let NCORE=0
	    let NNODE=NNODE+1
	fi
done


cat node.list
echo $NPROCS

echo done



mpirun.lsf ./Gadget2 impact.param > output0.txt 




