      PROGRAM ANEOSTEST
C
C      PROGRAM TO INITIALIZE ANEOS AND CALL IT ONCE
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      PARAMETER (NDENS=0)
      PARAMETER (NTEMP=0)
      DIMENSION IZETL(21)
      COMMON /FILEOS/ KLST, KINP
      COMMON /ANGELX/ W,Y,ALFA,BETA,DADT,DADR,DBDT,ZZ,ET,
     & SN,CVN,EN,PN,PM,EM,SM,CVM,EC,PC,RHO0,RHO00,ZVIB,
     & SMLT,CVMLT,EMLT,PMLT,H1,H2
      COMMON /ANEEL/ TEVX,RHOX,ABARX,ZBARM,T32X,FNX
     &  ,PE,EE,SE,CVE,DPTE,DPRE
     &  ,NMATSX,IIZX
      COMMON /ANEDIS/ GAMMA,PSI,THETA
      PARAMETER (MATBUF=64)
      COMMON /ANESQT/ SQTS(MATBUF),IPSQTS
      DIMENSION RHO(NDENS),TEMP(NTEMP),HISTDENS(100),HISTPRESS(100)
      DIMENSION HISTDPDR(100)
      DIMENSION TARR(233)
      DIMENSION DARR(339)
      DIMENSION PARR(339,233)
      DIMENSION SARR(339,233)
      DIMENSION EARR(339,233)
      DIMENSION CARR(339,233)
C
      OPEN(10,FILE='ANEOS.INPUT',STATUS='OLD')
      OPEN(12,FILE='ANEOS.OUTPUT')
      TCONV=1.16054D4
C
C     DEFINE ARRAYS OF DENSITY, TEMPERATURE
C
      DO 10 I=1,NDENS
      RHO(I)=10.D0**(1-I)
C      RHO(I)=1.11D0    !REFERENCE DENSITY
  10  CONTINUE
C
      DO 20 J=1,NTEMP
      TEMP(J)=1.D3*DFLOAT(J)/TCONV
C      TEMP(J)=2.008991D-2
  20  CONTINUE
C
C     INITIALIZE ANALYTIC EOS
C
      KLST=12
      KINP=10
      M=0
      IZETL(1)=-1
      CALL ANEOS2 (1,1,0,IZETL)
C
C     CALL ANEOS1 FOR ARRAY OF DENSITY, TEMPERATURE
C
C    INITIAL CALL FOR A SINGLE TEMP, DENSITY
C
C      TEMP1=3.D3/TCONV
C      RHO1=1.D-4
C      CALL ANEOS1 (TEMP1,RHO1,P,E,S,CV,DPDT,DPDR,M)
C
      DEL=1.D-3
      DELTA=1.D0+DEL
      DO 100 I=1,NDENS
      DO 200 J=1,NTEMP
C
C     CALL ANEOS FOR DIRECT CALCULATIONS
C
      IPSQTS=1    
      SQTS(IPSQTS)=DSQRT(TEMP(J))    !square root of temperature for aneos1
      CALL ANEOS1 (TEMP(J),RHO(I),P,E,S,CV,DPDT,DPDR,M)
      W0=W
      Y0=Y
      ZZ0=ZZ
      ZVIB0=ZVIB
      PSI0=PSI
      GAMMA0=GAMMA
      THETA0=THETA
      ALFA0=ALFA
      BETA0=BETA
      DBDT0=DBDT
      DADT0=DADT
      DADR0=DADR
C
C    DEFINE INTERMEDIATE QUANTITIES IN CONSTRUCTING THERMO QUANTITIES
C
      EMFRAC=EM
      ENFRAC=EN
      EEFRAC=EE
      ECFRAC=EC
      PMFRAC=PM
      PNFRAC=PN
      PEFRAC=PE
      PCFRAC=PC
      SMFRAC=SM
      SEFRAC=SE
      SNFRAC=SN
      CVMFRAC=CVM
      CVEFRAC=CVE
      CVNFRAC=CVN
C
C     CALL ANEOS TO COMPUTE DERIVATIVES DIRECTLY
C
      CALL ANEOS1 (TEMP(J),RHO(I)*DELTA,P2,E2,S2,CV2,DPDT2,DPDR2,M)
      ALFA2=ALFA
      ZZ2=ZZ
      SQTS(IPSQTS)=DSQRT(TEMP(J)*DELTA)
      CALL ANEOS1 (TEMP(J)*DELTA,RHO(I),P1,E1,S1,CV1,DPDT1,DPDR1,M)
      ALFA1=ALFA
      BETA1=BETA
      ZZ1=ZZ
C
      ALFAC=-1.5D0*(ZZ2-ZZ0)/(DEL*ZZ0)
      BETAC=(ZZ1-ZZ0)/(DEL*ZZ0)
C
      CVC=(E1-E)/(TEMP(J)*DEL)
      DPDTC=(P1-P)/(TEMP(J)*DEL)
      DPDRC=(P2-P)/(RHO(I)*DEL)
      DBDTC=(BETA1-BETA0)/DEL
      DADTC=(ALFA1-ALFA0)/DEL
      DADRC=(ALFA2-ALFA0)/DEL
C
      DSDR=(S2-S)/(RHO(I)*DEL)
      DPDT=(P1-P)/(TEMP(J)*DEL)
C
C    WRITE OUT RESULTS

C      WRITE(KLST,1000) RHO(I),TEMP(J)*TCONV
C      WRITE(KLST,2000) P,P2,E,E1,S,S2,CV,CVC,DPDT,DPDTC,DPDR,DPDRC
C      WRITE(KLST,3000) -DSDR*RHO(I)**2,DPDT
C      WRITE(KLST,4000) ZVIB0,Y0,W0,ZZ0,PSI0,GAMMA0,THETA0
C      WRITE(KLST,5000) ALFA0, ALFAC,BETA0,BETAC,
C     &         DADT0,DADTC,DADR0,DADRC,DBDT0,DBDTC,H1,H2
C      WRITE(KLST,9000) ECFRAC,ENFRAC,EMFRAC,EMLT,EEFRAC,
C     &                  PCFRAC,PNFRAC,PMFRAC,PMLT,PEFRAC,
C     &                         SNFRAC,SMFRAC,SMLT,SEFRAC,
C     &                         CVNFRAC,CVMFRAC,CVMLT,CVEFRAC
 200  CONTINUE
 100  CONTINUE
C
C     CALL ANEOS TO CONSTRUCT A TABLE OF THERMODYNAMIC FUNCTIONS AT 1 BAR
C
      PREF=1.D6      !REFERENCE PRESSURE =  1 ATMOSPHERE
      DENS0=1.9
      TOL=1.D-7      !PRECISION OF CONVERGENCE TO REF PRESSURE

      FIRST=1
      TCOUNT=1
      DCOUNT=1

!      WRITE(KLST, 6100)

!------------------------------------------------ region 1  150K < T < 1250K, 50K steps
      DO 300 J=3,25
      T=5.D1*DFLOAT(J)/TCONV  !50 DEGREE K STEPS
      TARR(TCOUNT) = T
      DO 400 K=1,50                               !-----------  Density region 1  10^-4 < rho < 1900 kg/m^3, log steps
      NUM=50-(K-1)
      DENS= DENS0 - (alog10(DFLOAT(NUM))/alog10(50)*(DENS0-1.D-7))
      CALL ANEOSV (1,T,DENS,1,P,E,S,CV,DPDT,DPDR,FKRO,CS,KPA,
     &  R2PL,R2PH,ZBAR)
      PARR(DCOUNT,TCOUNT) = P
      SARR(DCOUNT,TCOUNT) = S
      EARR(DCOUNT,TCOUNT) = E
      CARR(DCOUNT,TCOUNT) = CS
      DARR(DCOUNT) = DENS
      DCOUNT = DCOUNT + 1
!      WRITE(KLST,8100) T*TCONV,DENS*1.D3,P*1.D-10,E*1.D-4,
!     & S*(1.D-4/TCONV),KPA,J!ICOUNT
!      WRITE(KLST,8200) P*1.D-10, T*TCONV
  400 CONTINUE
      DO 301 K=1,280                               !----------- Density region 2 1925 < rho < 8900 kg/m^3, 25 kg/m^3 steps
      DENS = 2.5D-2*DFLOAT(K)+DENS0
      CALL ANEOSV (1,T,DENS,1,P,E,S,CV,DPDT,DPDR,FKRO,CS,KPA,
     &  R2PL,R2PH,ZBAR)
      PARR(DCOUNT,TCOUNT) = P
      SARR(DCOUNT,TCOUNT) = S
      EARR(DCOUNT,TCOUNT) = E
      CARR(DCOUNT,TCOUNT) = CS
      DARR(DCOUNT) = DENS
      DCOUNT = DCOUNT + 1
!      WRITE(KLST,8100) T*TCONV,DENS*1.D3,P*1.D-10,E*1.D-4,
!     & S*(1.D-4/TCONV),KPA,J!ICOUNT
!      WRITE(KLST,8200) P*1.D-10, T*TCONV
  301  CONTINUE
      DO 390 K=2,10                                !----------- Density region 3 9400 < rho < 20,000 kg/m^3, log steps
      NUM=10-(K-1)
      DENS2=20.-(alog10(DFLOAT(NUM))/alog10(10)*(20.-DENS))
      CALL ANEOSV (1,T,DENS2,1,P,E,S,CV,DPDT,DPDR,FKRO,CS,KPA,
     &  R2PL,R2PH,ZBAR)
      PARR(DCOUNT,TCOUNT) = P
      SARR(DCOUNT,TCOUNT) = S
      EARR(DCOUNT,TCOUNT) = E
      CARR(DCOUNT,TCOUNT) = CS
      DARR(DCOUNT) = DENS2
      DCOUNT = DCOUNT + 1
!      WRITE(KLST,8100) T*TCONV,DENS2*1.D3,P*1.D-10,E*1.D-4,
!     & S*(1.D-4/TCONV),KPA,NUM!ICOUNT
!      WRITE(KLST,8200) P*1.D-10, T*TCONV
  390 CONTINUE
      DCOUNT = 1
      TCOUNT = TCOUNT + 1
  300 CONTINUE

!------------------------------------------------ region 2  1250K < T < 3200K, 50K steps
      DO 302 J=1,39
      T2=T+(5.D1*DFLOAT(J))/TCONV
      TARR(TCOUNT) = T2
      DO 401 K=1,50
      NUM=50-(K-1)
      DENS= DENS0 - (alog10(DFLOAT(NUM))/alog10(50)*(DENS0-1.D-7))
      CALL ANEOSV (1,T2,DENS,1,P,E,S,CV,DPDT,DPDR,FKRO,CS,KPA,
     &  R2PL,R2PH,ZBAR)
      PARR(DCOUNT,TCOUNT) = P
      SARR(DCOUNT,TCOUNT) = S
      EARR(DCOUNT,TCOUNT) = E
      CARR(DCOUNT,TCOUNT) = CS
      DCOUNT = DCOUNT+1
!      WRITE(KLST,8100) T2*TCONV,DENS*1.D3,P*1.D-10,E*1.D-4,
!     & S*(1.D-4/TCONV),KPA,J!ICOUNT
!      WRITE(KLST,8200) P*1.D-10, T2*TCONV
 401  CONTINUE
      DO 303 K=1,280
      DENS = 2.5D-2*DFLOAT(K)+DENS0
      CALL ANEOSV (1,T2,DENS,1,P,E,S,CV,DPDT,DPDR,FKRO,CS,KPA,
     &  R2PL,R2PH,ZBAR)
      PARR(DCOUNT,TCOUNT) = P
      SARR(DCOUNT,TCOUNT) = S
      EARR(DCOUNT,TCOUNT) = E
      CARR(DCOUNT,TCOUNT) = CS
      DCOUNT = DCOUNT+1
!      WRITE(KLST,8100) T2*TCONV,DENS*1.D3,P*1.D-10,E*1.D-4,
!     & S*(1.D-4/TCONV),KPA,J!ICOUNT
!      WRITE(KLST,8200) P*1.D-10, T2*TCONV
 303  CONTINUE
      DO 392 K=2,10
      NUM=10-(K-1)
      DENS2=20.-(alog10(DFLOAT(NUM))/alog10(10)*(20.-DENS))
      CALL ANEOSV (1,T2,DENS2,1,P,E,S,CV,DPDT,DPDR,FKRO,CS,KPA,
     &  R2PL,R2PH,ZBAR)
      PARR(DCOUNT,TCOUNT) = P
      SARR(DCOUNT,TCOUNT) = S
      EARR(DCOUNT,TCOUNT) = E
      CARR(DCOUNT,TCOUNT) = CS
      DCOUNT = DCOUNT + 1
!      WRITE(KLST,8100) T2*TCONV,DENS2*1.D3,P*1.D-10,E*1.D-4,
!     & S*(1.D-4/TCONV),KPA,NUM!ICOUNT
!      WRITE(KLST,8200) P*1.D-10, T2*TCONV
 392  CONTINUE
      DCOUNT = 1
      TCOUNT = TCOUNT + 1
 302  CONTINUE

!----------------------------------------------- region 3 3220K < T < 3225K, 1K steps
      DO 304 J=1,5
      T2=(3219.+DFLOAT(J))/TCONV
      TARR(TCOUNT) = T2
      DO 402 K=1,50
      NUM=50-(K-1)
      DENS= DENS0 - (alog10(DFLOAT(NUM))/alog10(50)*(DENS0-1.D-7))
      CALL ANEOSV (1,T2,DENS,1,P,E,S,CV,DPDT,DPDR,FKRO,CS,KPA,
     &  R2PL,R2PH,ZBAR)
      PARR(DCOUNT,TCOUNT) = P
      SARR(DCOUNT,TCOUNT) = S
      EARR(DCOUNT,TCOUNT) = E
      CARR(DCOUNT,TCOUNT) = CS
      DCOUNT = DCOUNT + 1
!      WRITE(KLST,8100) T2*TCONV,DENS*1.D3,P*1.D-10,E*1.D-4,
!     & S*(1.D-4/TCONV),KPA,J!ICOUNT
!      WRITE(KLST,8200) P*1.D-10, T2*TCONV
 402  CONTINUE
      DO 305 K=1,280
      DENS = 2.5D-2*DFLOAT(K)+DENS0
      CALL ANEOSV (1,T2,DENS,1,P,E,S,CV,DPDT,DPDR,FKRO,CS,KPA,
     &  R2PL,R2PH,ZBAR)
      PARR(DCOUNT,TCOUNT) = P
      SARR(DCOUNT,TCOUNT) = S
      EARR(DCOUNT,TCOUNT) = E
      CARR(DCOUNT,TCOUNT) = CS
      DCOUNT = DCOUNT + 1
!      WRITE(KLST,8100) T2*TCONV,DENS*1.D3,P*1.D-10,E*1.D-4,
!     & S*(1.D-4/TCONV),KPA,J!ICOUNT
!      WRITE(KLST,8200) P*1.D-10, T2*TCONV
 305  CONTINUE
      DO 394 K=2,10
      NUM=10-(K-1)
      DENS2=20.-(alog10(DFLOAT(NUM))/alog10(10)*(20.-DENS))
      CALL ANEOSV (1,T2,DENS2,1,P,E,S,CV,DPDT,DPDR,FKRO,CS,KPA,
     &  R2PL,R2PH,ZBAR)
      PARR(DCOUNT,TCOUNT) = P
      SARR(DCOUNT,TCOUNT) = S
      EARR(DCOUNT,TCOUNT) = E
      CARR(DCOUNT,TCOUNT) = CS
      DCOUNT = DCOUNT + 1
!      WRITE(KLST,8100) T2*TCONV,DENS2*1.D3,P*1.D-10,E*1.D-4,
!     & S*(1.D-4/TCONV),KPA,NUM!ICOUNT
!      WRITE(KLST,8200) P*1.D-10, T2*TCONV
 394  CONTINUE
      DCOUNT = 1
      TCOUNT = TCOUNT + 1
 304  CONTINUE


!---------------------------------------------- region 4  3250K < T < 5500K, 25K steps
      DO 306 J=1,90
      T2=(3225.+2.5D1*DFLOAT(J))/TCONV
      TARR(TCOUNT) = T2
      DO 403 K=1,50
      NUM=50-(K-1)
      DENS= DENS0 - (alog10(DFLOAT(NUM))/alog10(50)*(DENS0-1.D-7))
      CALL ANEOSV (1,T2,DENS,1,P,E,S,CV,DPDT,DPDR,FKRO,CS,KPA,
     &  R2PL,R2PH,ZBAR)
      PARR(DCOUNT,TCOUNT) = P
      SARR(DCOUNT,TCOUNT) = S
      EARR(DCOUNT,TCOUNT) = E
      CARR(DCOUNT,TCOUNT) = CS
      DCOUNT = DCOUNT + 1
!      WRITE(KLST,8100) T2*TCONV,DENS*1.D3,P*1.D-10,E*1.D-4,
!     & S*(1.D-4/TCONV),KPA,J!ICOUNT
!      WRITE(KLST,8200) P*1.D-10, T2*TCONV
 403  CONTINUE
      DO 307 K=1,280
      DENS = 2.5D-2*DFLOAT(K)+DENS0
      CALL ANEOSV (1,T2,DENS,1,P,E,S,CV,DPDT,DPDR,FKRO,CS,KPA,
     &  R2PL,R2PH,ZBAR)
      PARR(DCOUNT,TCOUNT) = P
      SARR(DCOUNT,TCOUNT) = S
      EARR(DCOUNT,TCOUNT) = E
      CARR(DCOUNT,TCOUNT) = CS
      DCOUNT = DCOUNT + 1
!      WRITE(KLST,8100) T2*TCONV,DENS*1.D3,P*1.D-10,E*1.D-4,
!     & S*(1.D-4/TCONV),KPA,J!ICOUNT
!      WRITE(KLST,8200) P*1.D-10, T2*TCONV
 307  CONTINUE
      DO 396 K=2,10
      NUM=10-(K-1)
      DENS2=20.-(alog10(DFLOAT(NUM))/alog10(10)*(20.-DENS))
      CALL ANEOSV (1,T2,DENS2,1,P,E,S,CV,DPDT,DPDR,FKRO,CS,KPA,
     &  R2PL,R2PH,ZBAR)
      PARR(DCOUNT,TCOUNT) = P
      SARR(DCOUNT,TCOUNT) = S
      EARR(DCOUNT,TCOUNT) = E
      CARR(DCOUNT,TCOUNT) = CS
      DCOUNT = DCOUNT + 1
!      WRITE(KLST,8100) T2*TCONV,DENS2*1.D3,P*1.D-10,E*1.D-4,
!     & S*(1.D-4/TCONV),KPA,NUM!ICOUNT
!      WRITE(KLST,8200) P*1.D-10, T2*TCONV
 396  CONTINUE
      DCOUNT = 1
      TCOUNT = TCOUNT + 1
 306  CONTINUE



!---------------------------------------------- region 5  5750K < T < 10,000K, 250K steps
      DO 316 J=1,18
      T2=(5500.+2.5D2*DFLOAT(J))/TCONV
      TARR(TCOUNT) = T2
      DO 413 K=1,50
      NUM=50-(K-1)
      DENS= DENS0 - (alog10(DFLOAT(NUM))/alog10(50)*(DENS0-1.D-7))
      CALL ANEOSV (1,T2,DENS,1,P,E,S,CV,DPDT,DPDR,FKRO,CS,KPA,
     &  R2PL,R2PH,ZBAR)
      PARR(DCOUNT,TCOUNT) = P
      SARR(DCOUNT,TCOUNT) = S
      EARR(DCOUNT,TCOUNT) = E
      CARR(DCOUNT,TCOUNT) = CS
      DCOUNT = DCOUNT + 1
!      WRITE(KLST,8100) T2*TCONV,DENS*1.D3,P*1.D-10,E*1.D-4,
!     & S*(1.D-4/TCONV),KPA,J!ICOUNT
!      WRITE(KLST,8200) P*1.D-10, T2*TCONV, DENS*1.D3
 413  CONTINUE
      DO 317 K=1,280
      DENS = 2.5D-2*DFLOAT(K)+DENS0
      CALL ANEOSV (1,T2,DENS,1,P,E,S,CV,DPDT,DPDR,FKRO,CS,KPA,
     &  R2PL,R2PH,ZBAR)
      PARR(DCOUNT,TCOUNT) = P
      SARR(DCOUNT,TCOUNT) = S
      EARR(DCOUNT,TCOUNT) = E
      CARR(DCOUNT,TCOUNT) = CS
      DCOUNT = DCOUNT + 1
!      WRITE(KLST,8100) T2*TCONV,DENS*1.D3,P*1.D-10,E*1.D-4,
!     & S*(1.D-4/TCONV),KPA,J!ICOUNT
!      WRITE(KLST,8200) P*1.D-10, T2*TCONV
 317  CONTINUE
      DO 397 K=2,10
      NUM=10-(K-1)
      DENS2=20.-(alog10(DFLOAT(NUM))/alog10(10)*(20.-DENS))
      CALL ANEOSV (1,T2,DENS2,1,P,E,S,CV,DPDT,DPDR,FKRO,CS,KPA,
     &  R2PL,R2PH,ZBAR)
      PARR(DCOUNT,TCOUNT) = P
      SARR(DCOUNT,TCOUNT) = S
      EARR(DCOUNT,TCOUNT) = E
      CARR(DCOUNT,TCOUNT) = CS
      DCOUNT = DCOUNT + 1
!      WRITE(KLST,8100) T2*TCONV,DENS2*1.D3,P*1.D-10,E*1.D-4,
!     & S*(1.D-4/TCONV),KPA,NUM!ICOUNT
!      WRITE(KLST,8200) P*1.D-10, T2*TCONV
 397  CONTINUE
      DCOUNT = 1
      TCOUNT = TCOUNT + 1
 316  CONTINUE



!---------------------------------------------- region 6   19,800K < T < 10^6K, log steps
      T2=T2*TCONV

      DO 308 J=2,30
      NUM=30-(J-1)
      T3=(1.D6-(alog10(DFLOAT(NUM))/alog10(30.)*(1.D6-T2)))/TCONV
      TARR(TCOUNT) = T3
      DO 404 K=1,50
      NUM=50-(K-1)
      DENS= DENS0 - (alog10(DFLOAT(NUM))/alog10(50)*(DENS0-1.D-7))
      CALL ANEOSV (1,T3,DENS,1,P,E,S,CV,DPDT,DPDR,FKRO,CS,KPA,
     &  R2PL,R2PH,ZBAR)
      PARR(DCOUNT,TCOUNT) = P
      SARR(DCOUNT,TCOUNT) = S
      EARR(DCOUNT,TCOUNT) = E
      CARR(DCOUNT,TCOUNT) = CS
      DCOUNT = DCOUNT + 1
!      WRITE(KLST,8100) T3*TCONV,DENS*1.D3,P*1.D-10,E*1.D-4,
!     & S*(1.D-4/TCONV),KPA,J!ICOUNT
!      WRITE(KLST,8200) P*1.D-10, T3*TCONV
 404  CONTINUE
      DO 309 K=1,280
      DENS = 2.5D-2*DFLOAT(K)+DENS0
      CALL ANEOSV (1,T3,DENS,1,P,E,S,CV,DPDT,DPDR,FKRO,CS,KPA,
     &  R2PL,R2PH,ZBAR)
      PARR(DCOUNT,TCOUNT) = P
      SARR(DCOUNT,TCOUNT) = S
      EARR(DCOUNT,TCOUNT) = E
      CARR(DCOUNT,TCOUNT) = CS
      DCOUNT = DCOUNT + 1
!      WRITE(KLST,8100) T3*TCONV,DENS*1.D3,P*1.D-10,E*1.D-4,
!     & S*(1.D-4/TCONV),KPA,NUM!ICOUNT
!      WRITE(KLST,8200) P*1.D-10, T3*TCONV
 309  CONTINUE
      DO 398 K=2,10
      NUM=10-(K-1)
      DENS2=20.-(alog10(DFLOAT(NUM))/alog10(10)*(20.-DENS))
      CALL ANEOSV (1,T3,DENS2,1,P,E,S,CV,DPDT,DPDR,FKRO,CS,KPA,
     &  R2PL,R2PH,ZBAR)
      PARR(DCOUNT,TCOUNT) = P
      SARR(DCOUNT,TCOUNT) = S
      EARR(DCOUNT,TCOUNT) = E
      CARR(DCOUNT,TCOUNT) = CS
      DCOUNT = DCOUNT + 1
!      WRITE(KLST,8100) T3*TCONV,DENS2*1.D3,P*1.D-10,E*1.D-4,
!     & S*(1.D-4/TCONV),KPA,NUM!ICOUNT
!      WRITE(KLST,8200) P*1.D-10, T3*TCONV
 398  CONTINUE
      DCOUNT = 1
      TCOUNT = TCOUNT + 1
 308  CONTINUE



!---------------------------------------------- region 7  10^6K < T < 10^8K, log steps
      T3=T3*TCONV

      DO 310 J=2,30
      NUM=30-(J-1)
      T4=(1.D8-(alog10(DFLOAT(NUM))/alog10(30.)*(1.D8-T3)))/TCONV
      TARR(TCOUNT) = T4
      DO 405 K=1,50
      NUM=50-(K-1)
      DENS= DENS0 - (alog10(DFLOAT(NUM))/alog10(50)*(DENS0-1.D-7))
      CALL ANEOSV (1,T4,DENS,1,P,E,S,CV,DPDT,DPDR,FKRO,CS,KPA,
     &  R2PL,R2PH,ZBAR)
      PARR(DCOUNT,TCOUNT) = P
      SARR(DCOUNT,TCOUNT) = S
      EARR(DCOUNT,TCOUNT) = E
      CARR(DCOUNT,TCOUNT) = CS
      DCOUNT = DCOUNT + 1
!      WRITE(KLST,8100) T4*TCONV,DENS*1.D3,P*1.D-10,E*1.D-4,
!     & S*(1.D-4/TCONV),KPA,J!ICOUNT
!      WRITE(KLST,8200) P*1.D-10, T4*TCONV
 405  CONTINUE
      DO 311 K=1,280
      DENS = 2.5D-2*DFLOAT(K)+DENS0
      CALL ANEOSV (1,T4,DENS,1,P,E,S,CV,DPDT,DPDR,FKRO,CS,KPA,
     &  R2PL,R2PH,ZBAR)
      PARR(DCOUNT,TCOUNT) = P
      SARR(DCOUNT,TCOUNT) = S
      EARR(DCOUNT,TCOUNT) = E
      CARR(DCOUNT,TCOUNT) = CS
      DCOUNT = DCOUNT + 1
!      WRITE(KLST,8100) T4*TCONV,DENS*1.D3,P*1.D-10,E*1.D-4,
!     & S*(1.D-4/TCONV),KPA,NUM!ICOUNT
!      WRITE(KLST,8200) P*1.D-10, T4*TCONV
 311  CONTINUE
      DO 395 K=2,10
      NUM=10-(K-1)
      DENS2=20.-(alog10(DFLOAT(NUM))/alog10(10)*(20.-DENS))
      CALL ANEOSV (1,T4,DENS2,1,P,E,S,CV,DPDT,DPDR,FKRO,CS,KPA,
     &  R2PL,R2PH,ZBAR)
      PARR(DCOUNT,TCOUNT) = P
      SARR(DCOUNT,TCOUNT) = S
      EARR(DCOUNT,TCOUNT) = E
      CARR(DCOUNT,TCOUNT) = CS
      DCOUNT = DCOUNT + 1
!      WRITE(KLST,8100) T4*TCONV,DENS2*1.D3,P*1.D-10,E*1.D-4,
!     & S*(1.D-4/TCONV),KPA,NUM!ICOUNT
!      WRITE(KLST,8200) P*1.D-10, T4*TCONV
 395  CONTINUE
      IF (J .NE. 30) DCOUNT = 1
      TCOUNT = TCOUNT + 1
 310  CONTINUE


! Units should be:  T in K, rho in g/cm^3, P in GPa, S in MJ/kg-K, E in MJ/kg


      WRITE(KLST,8250) DCOUNT-1, TCOUNT-1
      STYLE=2

      DO 322 K=1, DCOUNT-1
      WRITE(KLST,8250) DARR(K)
      STYLE=STYLE+1
      IF (mod(STYLE,5) .EQ. 0) WRITE(KLST,8200)
 322  CONTINUE

      DO 321 J=1, TCOUNT-1
      WRITE(KLST,8250) TARR(J)*TCONV
      STYLE=STYLE+1
      IF (mod(STYLE,5) .EQ. 0) WRITE(KLST,8200)
 321  CONTINUE


      DO 323 J=1, TCOUNT-1
      DO 324 K=1, DCOUNT-1
      IF (PARR(K,J) .LT. 1.D-10 .AND. PARR(K,J) .GT. 0.) PARR(K,J)=1.D-0
      WRITE(KLST,8250) PARR(K,J)*1.D-10
      STYLE=STYLE+1
      IF (mod(STYLE,5) .EQ. 0) WRITE(KLST,8200)
 324  CONTINUE
 323  CONTINUE


      DO 327 J=1, TCOUNT-1
      DO 328 K=1, DCOUNT-1
      WRITE(KLST,8250) EARR(K,J)*1.D-10
      STYLE=STYLE+1
      IF (mod(STYLE,5) .EQ. 0) WRITE(KLST,8200)
 328  CONTINUE
 327  CONTINUE


      DO 325 J=1, TCOUNT-1
      DO 326 K=1, DCOUNT-1
      WRITE(KLST,8250) SARR(K,J)*(1.D-10/TCONV)
      STYLE=STYLE+1
      IF (mod(STYLE,5) .EQ. 0) WRITE(KLST,8200)
 326  CONTINUE
 325  CONTINUE


      DO 335 J=1, TCOUNT-1
      DO 336 K=1, DCOUNT-1
      WRITE(KLST,8250) CARR(K,J)
      STYLE=STYLE+1
      IF (mod(STYLE,5) .EQ. 0) WRITE(KLST,8200)
 336  CONTINUE
 335  CONTINUE



C
C    CALL ANEOS TO COMPUTE AND PRINT THE COLD PRESSURE FOR A RANGE OF DENSITY
C
      DENS0=RHO00    !REFERENCE DENSITY AT ZERO TEMPERATURE
      NDENSIT=100
      DMIN=5.D-2
      DMAX=5.0D0
      DINC=(DMAX-DMIN)/DFLOAT(NDENSIT-1)
!      WRITE(KLST,8300)
      DO 500 J=1,NDENSIT
      DENS=DMIN+DINC*DFLOAT(J-1)
      ETA=DENS/DENS0
      CALL ANEOS1 (1.D-6,DENS,P,E,S,CV,DPDT,DPDR,M)
      GCOLD=E+P/DENS
!      WRITE(KLST,8500) DENS,P,E,GCOLD,DPDR,ETA
500   CONTINUE
      STOP
C
1000  FORMAT(///'DENSITY = ',1PE15.5,'  TEMP(K) = ',1PE15.5//)
2000  FORMAT('  ANALYTIC COMPUTATIONAL RESULTS FROM ANEOS1'// 
     &'       PRESSURE = ',1PE15.5,'   AT RHO+DELTA RHO  = ',1PE15.5/
     &'       ENERGY   = ',1PE15.5,'   AT T+DELTA T      = ',1PE15.5/
     &'       ENTROPY  = ',1PE15.5,'   AT RHO+DELTA RHO  = ',1PE15.5/
     &'       HEAT CAP = ',1PE15.5,'   APPROX DERIVATIVE = ',1PE15.5/
     &'       DPDT     = ',1PE15.5,'   APPROX DERIVATIVE = ',1PE15.5/
     &'       DPDR     = ',1PE15.5,'   APPROX DERIVATIVE = ',1PE15.5)
3000  FORMAT(//'  TEST OF SECOND DERIVATIVES--THESE SHOULD BE EQUAL'// 
     &'       -DSDR*RHO**2 = ',1PE15.5/   
     &'        DPDT        = ',1PE15.5)
4000  FORMAT(//'  BOUND STATE AND EOS FACTORS'//
     &'       ZVIB FUNC = ',1PE15.5/
     &'       FACTOR Y  = ',1PE15.5/
     &'       UNBOUND W = ',1PE15.5/
     &'       RENORM Z  = ',1PE15.5/
     &'       PSI       = ',1PE15.5/
     &'       GAMMA     = ',1PE15.5/
     &'       THETA     = ',1PE15.5/)
5000  FORMAT(//'  INTERMEDIATE QUANTITIES FOR MOLECULAR COMPUTATION'//
     &'       ALPHA     = ',1PE15.5,'   APPROX DERIVATIVE = ',1PE15.5/
     &'       BETA      = ',1PE15.5,'   APPROX DERIVATIVE = ',1PE15.5/
     &'       DADT      = ',1PE15.5,'   APPROX DERIVATIVE = ',1PE15.5/
     &'       DADR      = ',1PE15.5,'   APPROX DERIVATIVE = ',1PE15.5/
     &'       DBDT      = ',1PE15.5,'   APPROX DERIVATIVE = ',1PE15.5/
     &'       H1        = ',1PE15.5/
     &'       H2        = ',1PE15.5)
6000  FORMAT(//' THERMODYNAMIC FUNCTIONS OF TEMPERATURE AT 1 BAR,'//
     & '        TEMP         DENSITY       PRESSURE       ENERGY',
     & '         ENTHALPY        ENTROPY        GIBBS       PHASE',
     & '     #ITER'/
     & '         K           kg/m**3         GPa            J/kg',
     & '           J/kg           J/kg-K         J/kg'/)
6100  FORMAT(//' THERMODYNAMIC FUNCTIONS OF TEMPERATURE AT 1 BAR,'//
     & '        TEMP         DENSITY       PRESSURE       ENERGY',
     & '         ENTROPY       PHASE',
     & '     #ITER'/
     & '         K           kg/m**3         GPa            J/kg',
     & '         J/kg-K '/)
7000  FORMAT(//' PRESSURE ITERATION FAILS TO CONVERGE AFTER ',
     & I5,' STEPS'//)
8000  FORMAT(7(1PE15.5),5X,I2,5X,I5)
8100  FORMAT(5(1PE15.5),5X,I2,5X,I5)
8200  FORMAT(3(1PE15.8))
8250  FORMAT(1(1PE15.8), $)
8300  FORMAT(//' COLD PRESSURE DEPENDENCE ON DENSITY, CGS UNITS'//
     &'       DENSITY       PRESSURE       ENERGY         GIBBS',
     &'           DPDR           ETA'/)
8500  FORMAT(6(1PE15.5))
8700  FORMAT(/'ITERATION HISTORY:'/' STEP#    DENSITY      PRESSURE   ',
     &'   DPDR'/)
8900  FORMAT(I5,3(1PE15.5))
9000  FORMAT(//' INDIVIDUAL CONTRIBUTIONS TO THERMODYNAMIC FUNCTIONS:'//
     &'  QUANTITY         COLD          NUCLEAR      MOLECULAR',
     &'         MELT        ELECTRONIC'//
     &'   ENERGY   ',5(1PE15.5)/
     &'   PRESSURE ',5(1PE15.5)/
     &'   ENTROPY  ',15X,4(1PE15.5)/
     &'   HEAT CAP.',15X,4(1PE15.5))
C
      END

