#!/bin/sh
#BSUB -q shock
#BSUB -J gad1run
#BSUB -n 8
#BSUB -u sstewart@eps.harvard.edu
#BSUB -o file.out
#BSUB -e file.err
#BSUB -a openmpi
#BSUB -N



ulimit -l unlimited

cp $LSB_DJOB_HOSTFILE node.list
let NPROC=0
let NNODE=0
let NCORE=0

for machine in `cat $LSB_DJOB_HOSTFILE`
do
        let NPROC=NPROC+1
	let NCORE=NCORE+1
	if [ $NCORE == 8 ];
	then
	    let NCORE=0
	    let NNODE=NNODE+1
	fi
done


cat node.list
echo $NPROCS

echo done



mpirun.lsf ./Gadget2 impact.param > output0.txt 




